### ISSUE TITLE
fetchFlagSettings doesnt update in memory flags or emit any events

### ISSUE THREAD

**Issue by maxholman** [launchdarkly/js-client#72]
If you are bootstrapping from localStorage, it is possible to have a situation where both localStorage and the in-memory flags are out of sync with the latest response that the client has received.

There is a [comment in the code](https://github.com/launchdarkly/js-client/blob/4fd7e8061fc963be60f034ae044866aee3eebe03/src/index.js#L324) that explains:

```javascript
// We won't signal changes or update the in-memory flags unless you subscribe for changes
```

But, even if you do subscribe for changes as suggested, there is no code that fires off a `change` event.  Only localStorage is updated.

It's therefore not possible to react to these new/changed values until next refresh when the client reads from localStorage again and sees the new values.

Related: #59

**Comment by apucacao** [comment]
Hi @maxholman ,

Thanks for reaching out.

We only connect to the stream for updates if you [subscribe to the `change` event](https://github.com/launchdarkly/js-client/blob/4fd7e8061fc963be60f034ae044866aee3eebe03/src/index.js#L228). When updates from the stream arrive — and you bootstrapped using `localStorage` — [the client will update that cache](https://github.com/launchdarkly/js-client/blob/4fd7e8061fc963be60f034ae044866aee3eebe03/src/index.js#L206) to ensure the next refresh `localStorage` contains the last known settings from the server. 

Does that make sense?

Best,
Alexis

**Comment by maxholman** [comment]
Thanks @apucacao - gotcha.

How can I get my app to react to these changes that are *not* streamed in, and are also *not* in localStorage at bootstrap time?

Calling `getFlags` on `ready` returns the in-memory state which can be stale (not the same as localStorage or the server state)

It seems like the purpose of the `change` event is to notify subscribers simply that flags have changed.  Should it not be emitted both when changes arrive through the stream (as you mentioned) but also when `fetchFlagSettings` updates localStorage?

**Comment by apucacao** [comment]
Ah, I see. Do you subscribe to `change` in your application? If you do, then you should get the latest settings from the server upon connecting to the stream. (We fetch once on connect.) Am I understanding correctly? Is that not working?

If you don't subscribe to `change`, then we have no way of letting you know that the latest settings we received were different from those you got from calling `allFlags` on `ready`. And to avoid discrepancies between calls to `variation` and the initial state you got on `ready`, we don't update the in-memory state.

**Comment by maxholman** [comment]
My `change` subscription is working as expected for when something comes across the stream.

After some more digging, it looks like [`stream.connect` callback](https://github.com/launchdarkly/js-client/blob/4fd7e8061fc963be60f034ae044866aee3eebe03/src/index.js#L185) isn't firing for me on connect, but only when some inbound event arrives.

I'll see if I can troubleshoot more from here,  but essentially this means that the `fetchFlagSettings` and `updateSettings` doesn't get called when the stream connects and therefore no `change` event occurs, causing the issue as described.

**Comment by maxholman** [comment]
Looks like there are no `ping` events occuring on the stream until I make a change on launchdarkly.com - so the [`onPing`](https://github.com/launchdarkly/js-client/blob/4fd7e8061fc963be60f034ae044866aee3eebe03/src/Stream.js#L9) callback which is set via `stream.connect()` and updates the settings, doesnt fire when the stream connects.

**Comment by maxholman** [comment]
This seems to be happening:

1. Client is initialised
2. `flags` is populated from `localStorage`
3. `fetchFlagSettings` called to get latest response from server
4.  (async) `localStorage` is updated with latest response (no events are emitted and `flags` may be stale)
5. I register a `change` event listener
6. (async) Stream connects automatically due to event listener attach

At this point `localStorage` has the latest response, but `flags` is stale and reflects the state of `localStorage` on load.

I was expecting either:

a) Step 4 would emit a `change` event and update the in-memory flags, or
b) Step 6 should result in an initial `ping` event being received which then calls the `stream.connect` callback -> `fetchFlagSettings` -> `updateSettings` and finally `emit('change')`

Unfortunately neither of those happen so I am unable to get the absolute latest flags on load.

**Comment by apucacao** [comment]
Hi @maxholman, sorry for the delay here. This looks like a bug. I've added it to the list, and we should have a fix out shortly. I'll let you know once we've released a fix.

**Comment by apucacao** [comment]
Hi @maxholman — we should be sending the initial `ping` even again. Have you tried this recently?

**Comment by maxholman** [comment]
Hi @apucacao - Just tried this again, still not seeing an initial ping and I still have the same issue I'm afraid
